// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmAoRkYwQ_F5P-DeeZ1cG259ugVkB8AM',
    appId: '1:7532452806:web:6fdc731a44a0647d9470c7',
    messagingSenderId: '7532452806',
    projectId: 'bmi-test-c1d4b',
    authDomain: 'bmi-test-c1d4b.firebaseapp.com',
    storageBucket: 'bmi-test-c1d4b.appspot.com',
    measurementId: 'G-BV5BMKE237',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDpNYM9o8bYIfiUCY7tmV6jalPJjhXE8A',
    appId: '1:7532452806:android:88da62d487f736499470c7',
    messagingSenderId: '7532452806',
    projectId: 'bmi-test-c1d4b',
    storageBucket: 'bmi-test-c1d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElUjSJGf6Swt-AMIYkiF1EN4JNP7z8TQ',
    appId: '1:7532452806:ios:284edb7c3725d7689470c7',
    messagingSenderId: '7532452806',
    projectId: 'bmi-test-c1d4b',
    storageBucket: 'bmi-test-c1d4b.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElUjSJGf6Swt-AMIYkiF1EN4JNP7z8TQ',
    appId: '1:7532452806:ios:284edb7c3725d7689470c7',
    messagingSenderId: '7532452806',
    projectId: 'bmi-test-c1d4b',
    storageBucket: 'bmi-test-c1d4b.appspot.com',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnmAoRkYwQ_F5P-DeeZ1cG259ugVkB8AM',
    appId: '1:7532452806:web:59c58a7394ec58859470c7',
    messagingSenderId: '7532452806',
    projectId: 'bmi-test-c1d4b',
    authDomain: 'bmi-test-c1d4b.firebaseapp.com',
    storageBucket: 'bmi-test-c1d4b.appspot.com',
    measurementId: 'G-XY149RWLJ8',
  );
}
